# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run
      run: dotnet run --no-build --verbosity normal
    - name: Upload HtmlValidator artifact
      uses: actions/upload-artifact@v4
      with:
        name: HtmlValidator-${{ matrix.os }}.json
        path: bin/Debug/net8.0/HtmlValidator-output/*.json
    - name: Upload HtmlValidateCli-stdout artifact
      uses: actions/upload-artifact@v4
      with:
        name: HtmlValidateCli-stdout-${{ matrix.os }}.json
        path: bin/Debug/net8.0/HtmlValidateCli-stdout-output/*.json
    - name: Upload HtmlValidateCli-file artifact
      uses: actions/upload-artifact@v4
      with:
        name: HtmlValidateCli-file-${{ matrix.os }}.json
        path: bin/Debug/net8.0/HtmlValidateCli-file-output/*.json
